encoding: 'utf-8'


# SITE / COMPANY SETTINGS
lang: ru

title: PR-агентство «Полилог»
short_name: Polylog

description: >-
  Комплексное пиар-сопровождение. Организация мероприятий, event-менеджмент.
  IT и научные исследования для органов власти. Создаем интерес и уважение.

# The base hostname & protocol for the site without a trailing slash,
# e.g. https://example.tld
# url: https://www.polylog.ru
url: https://polylog.netlify.app

# the subpath of the site, e.g. /blog
baseurl: ''
assets: /a
# assets: https://assets.polylog.ru

# Permalink format (/blog/ is ignored for pages)
# permalink: /blog/:title

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

logo: /img/logo/polylog-logo.svg
image: /img/polylog.png
icon: /img/graphics/icon.png
# ui_sprite: /img/graphics/sprite.svg
color: '#ff6633'

# fonts: Cormorant+Garamond:wght@500&family=Inter:wght@300;400;600
# fonts: Cormorant+Garamond:ital,wght@1,600&family=Roboto:wght@100;300;400;500
fonts: Cormorant+Garamond:600%7CRoboto:100,300,400,500&amp;subset=cyrillic
rss_title: Новости пиар-агентства «Полилог»

gtm: GTM-P4R6SM7
apple_app_id: ''

# Site content creator / author Twitter @username
author: '@supervova'

permalink: /:slug
# permalink: /:year-:month-:day-:title/

# Ruby Date Format
date_format: '%-d %B, %Y'
timezone: Europe/Moscow

livereload: true

# ------------------------------------------------------------------------------

# Advanced Settings

jekyll_tidy:
  # exclude: ["index.html"]
  ignore_env: development
  compress_html: true

# Extended markdown letting use CSS classes: {:.btn .btn–primary}
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections_dir: collections
collections:
  blog:
    output: true
    permalink: /ru/pr-blog/:year/:slug
    sort_by: date
  projects-ru:
    output: true
    permalink: /ru/projects/:year/:slug
    sort_by: date
  projects-en:
    output: true
    permalink: /en/projects/:year/:slug
    sort_by: date
  news-ru:
    output: true
    permalink: /ru/news/:year/:slug
    sort_by: date
  tutorials:
    output: true
    permalink: /ru/tutorials/:slug
    sort_by: date
  help:
    output: true
    permalink: /ru/help/:slug

# Pagination Settings: jekyll-paginate-v2
autopages:
  enabled: true

  categories:
    enabled: true
    layouts:
      - index-category.html
    # slugify:
    #   mode: 'default'
    #   cased: true
    title: ':cat'
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/ru/pr-blog/:cat'

  collections:
    enabled: false

  tags:
    enabled: false

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
