encoding: 'utf-8'


# SITE / COMPANY SETTINGS
lang: ru

title: PR-агентство «Полилог»
short_name: Polylog

description: >-
  Комплексное пиар-сопровождение. Организация мероприятий, event-менеджмент.
  IT и научные исследования для органов власти. Создаем интерес и уважение.

# The base hostname & protocol for the site without a trailing slash,
# e.g. https://example.tld
# url: https://www.polylog.ru
url: https://polylog.netlify.app

# the subpath of the site, e.g. /blog
baseurl: ''
assets: /a
# assets: https://assets.polylog.ru

# Permalink format (/blog/ is ignored for pages)
# permalink: /blog/:title

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

logo: /img/logo/polylog-logo.svg
image: /img/polylog.png
icon: /img/graphics/icon.png
# ui_sprite: /img/graphics/sprite.svg
color: '#ff6633'

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
