# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

# Первая попытка
# media_folder: a/upload/blog # Folder where user uploaded files should go

# Вторая попытка
# media_folder: src/img/blog # Folder where user uploaded files should go
# public_folder: /upload/blog

# Третья попытка
# media_folder: _site/a/upload/blog # Folder where user uploaded files should go
# public_folder: upload/blog # Folder where user uploaded files should go

# Четвертая попытка.
media_folder: _site/a/upload/blog # Folder where user uploaded files should go

# Prevent timezones conflicts
future: true

# slug:
#   encoding: 'ascii'
#   clean_accents: true

collections:
  - label: 'Запись в блоге'
    name: 'blog'
    folder: 'collections/_blog/2020'
    create: true
    sort: 'date:desc' # Default is title:asc
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # fields.slug means 'field `slug` in front matter'
    editor:
      preview: false

    # The fields each document in this collection have
    # Additional widgets: code, boolean, file, map, number, object, relation,
    # select, text - www.netlifycms.org/docs/widgets
    fields:
      - { label: 'Макет', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Заголовок', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Темы'
        name: 'categories'
        widget: 'select'
        multiple: true
        min: 1
        max: 3
        options:
          - 'Event-менеджмент'
          - 'GR'
          - 'Диджитал-маркетинг'
          - 'Журналистика'
          - 'Классика по средам'
          - 'Маркетинг'
          - 'Менеджмент'
          - 'Пиар (PR)'
          - 'Промо-кампании'
          - 'Реклама'
        default: ['Пиар (PR)']

      # - { label: 'Название страницы в веб-адресе (латиницей, строчными, через дефис)', name: 'slug', widget: 'string' }
      - { label: 'Основная иллюстрация', name: 'image', widget: 'image', required: false }
      - { label: 'Первый абзац', name: 'description', widget: 'text' }
      - label: 'Основной текст (без первого абзаца)'
        name: 'body'
        widget: 'markdown'
        buttons: ['heading-two', 'heading-three', 'link', 'bold', 'italic', 'bulleted-list', 'numbered-list']
        required: false
      # Попытка №2
      # - { label: 'URL', name: 'permalink', widget: 'string', default: '/ru/pr-blog/{{year}}/{{slug}}' }
      # Попытка №3
      # - { label: 'URL', name: 'permalink', widget: 'string', default: '/ru/pr-blog/:year/:slug' }
      # Попытка №4 - без пермалинка вообще
      # Попытка №5 - проверка одновременно двух ситаксисов: {{}} и :
      - { label: 'Дата публикации', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD'}

    # PAGES
    # - name: 'page'
    #   label: 'Page'
    #   folder: 'pages'
    #   etc

    view_filters:
      # - label: 'Alice's and Bob's Posts'
      #   field: author
      #   pattern: 'Alice|Bob'
      - label: 'Записи за 2020'
        field: date
        pattern: '2020'
