backend:
  # name: github
  # repo: polylog/polylog-2020
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (optional; master is default, do we can leave this line out)

media_folder: 'a/upload/blog'
# media_folder: 'src/img/blog'

# Prevent timezones conflicts
future: true

slug:
  encoding: 'ascii'
  clean_accents: true

editor:
  preview: false

collections: # A list of collections the CMS should be able to edit
  - name: 'blog' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Запись в блоге' # Used in the UI, ie.: "New запись в блоге"
    folder: 'collections/_blog/2020' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    sort: 'date:desc' # Default is title:asc
    slug: '{{ year }}-{{ month }}-{{ day }}-{{ slug }}' # fields.slug means 'field `slug` in front matter'

    # The fields each document in this collection have
    # Additional widgets: code, boolean, file, map, number, object, relation,
    # select, text - www.netlifycms.org/docs/widgets
    fields:
    - { label: 'Макет', name: 'layout', widget: 'hidden', default: 'post' }
    # - { label: 'Название страницы в веб-адресе (латиницей, строчными, через дефис)', name: 'slug', widget: 'string' }
    - label: 'Категории'
      name: 'categories'
      widget: 'list'
      fields:
        - { label: 'Event-менеджмент', value: 'Event-менеджмент' }
        - { label: 'GR', value: 'GR' }
        - { label: 'Диджитал-маркетинг', value: 'Диджитал-маркетинг' }
        - { label: 'Журналистика', value: 'Журналистика' }
        - { label: 'Классика по средам', value: 'Классика по средам' }
        - { label: 'Маркетинг', value: 'Маркетинг' }
        - { label: 'Менеджмент', value: 'Менеджмент' }
        - { label: 'Пиар (PR)', value: 'Пиар (PR)' }
        - { label: 'Промо-кампании', value: 'Промо-кампании' }
        - { label: 'Реклама', value: 'Реклама' }
    - { label: 'Дата публикации', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD'}
    - { label: 'Заголовок', name: 'title', widget: 'string', tagname: 'h1' }
    - { label: 'Основная иллюстрация', name: 'thumbnail', widget: 'image', required: false }
    - { label: 'Первый абзац', name: 'description', widget: 'markdown' }
    - label: 'Основной текст (без первого абзаца)'
      name: 'body'
      widget: 'markdown'
      buttons: ['heading-two', 'heading-three', 'link', 'bold', 'italic', 'bulleted-list', 'numbered-list']
      required: false

    # PAGES
  # - name: "page"
  #   label: "Page"
  #   folder: "pages"
  #   etc

options:
  - { label: "Администратор", value: "admin" }
  - { label: "Валерия Исакова", value: "valeriya_isakova" }

view_filters:
  # - label: "Alice's and Bob's Posts"
  #   field: author
  #   pattern: 'Alice|Bob'
  - label: 'Записи за 2020'
    field: date
    pattern: '2020'
