# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: src/img/blog # Media files will be stored in the repo under src/img/blog
public_folder: /img/blog # The src attribute for uploaded media will begin with /img/blog

# Prevent timezones conflicts
future: true

# slug:
#   encoding: 'ascii'
#   clean_accents: true

collections:
  - label: 'Запись в блоге'
    name: 'blog'
    folder: 'collections/_blog/2020'
    create: true
    sort: 'date:desc' # Default is title:asc
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # fields.slug means 'field `slug` in front matter'
    editor:
      preview: false

    # The fields each document in this collection have
    # Additional widgets: code, boolean, file, map, number, object, relation,
    # select, text - www.netlifycms.org/docs/widgets
    fields:
      - { label: 'Макет', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Заголовок', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Веб-адрес'
        name: 'permalink'
        widget: 'string'
        default: '/ru/pr-blog/2020/'
        hint: 'Наберите в поле, после закрывающего слеша надписи "/ru/pr-blog/2020/" заголовок латиницей, строчными буквами. Пробелы замените дефисами. Не используйте апостроф и другие специальные символы. Или воспользуйтесь <a href="http://www.translityandex.ru/" target="_blank" rel="noopener noreferrer">онлайн-сервисом транслитерации</a>. Набранная строка будет адресом страницы в интернете.'
      - label: 'Темы'
        name: 'categories'
        widget: 'select'
        multiple: true
        min: 1
        max: 3
        options:
          - 'Event-менеджмент'
          - 'GR'
          - 'Диджитал-маркетинг'
          - 'Журналистика'
          - 'Классика по средам'
          - 'Маркетинг'
          - 'Менеджмент'
          - 'Пиар (PR)'
          - 'Промо-кампании'
          - 'Реклама'
        default: ['Пиар (PR)']
      - { label: 'Основная иллюстрация', name: 'image', widget: 'image', allow_multiple: false, required: false }
      - { label: 'Первый абзац', name: 'description', widget: 'text', hint: 'Этот параграф будет не только открывать статью, но и вместе с заголовком появляться в результатах поиска и ленте блога.' }
      - label: 'Основной текст (без первого абзаца)'
        name: 'body'
        widget: 'markdown'
        buttons: ['heading-two', 'heading-three', 'link', 'bold', 'italic', 'bulleted-list', 'numbered-list']
        required: false
      - { label: 'Дата публикации', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD'}


    # PAGES
    # - name: 'page'
    #   label: 'Page'
    #   folder: 'pages'
    #   etc

    view_filters:
      # - label: 'Alice's and Bob's Posts'
      #   field: author
      #   pattern: 'Alice|Bob'
      - label: 'Записи за 2020'
        field: date
        pattern: '2020'
